### PR TITLE
Use openshift build tools

### PR DESCRIPTION
**Pull request by jhernand**
This pull request contains the changes needed to use the standard
Go tooling used in OpenShift projects.

Fixes https://github.com/openshift/autoheal/issues/2

### CODE REVIEW

**Comment by jhernand** [comment]
@ironcladlou, @moolitayer, @zgalor, @elad661 please review.

Please note that the first three commits are huge, specially the ones that add
the vendor dependencies and the standard unmodified tooling. Please focus
your review on the last one, which is the one that adapts the project to use
the standard tooling.

**Comment by jhernand** [comment]
@ironcladlou when this is eventually merged, what do we need to do to build/test it in the OpenShift CI infrastructure?

**Comment by ironcladlou** [comment]
We'll have to follow the path set forth in https://trello.com/c/g66AI8Rd for CI integration. In the meantime, verify that the following work for you:
```
$ make
$ make build-images
```

**Comment by jhernand** [comment]
Yes, I have already verified `make` and `make build-images` in my environment, both work.

**Comment by ironcladlou** [comment]
If the important `make` targets work, let's merge and move on. It'll be up to you to gatekeep PRs and acting as a human CI bot until we have proper integration and tests 😆

**Comment by jhernand** [comment]
OK, great, thanks @ironcladlou ! I am merging.

**Comment by elad661** [comment]
Note that the go version check is not working very well,

```
[elad@eladalfassa-t470s autoheal]$ make
hack/build-go.sh  
[FATAL] Detected Go version: go version go1.10 linux/amd64.
[FATAL] Builds require Go version go1.9 or greater.
[ERROR] PID 13984: hack/lib/build/binaries.sh:155: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/binaries.sh:155: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )`
[INFO] 		  2: hack/build-go.sh:20: os::build::build_binaries
[INFO]   Exiting with code 1.
[ERROR] hack/build-go.sh exited with code 1 after 00h 00m 00s
make: *** [Makefile:41: all] Error 1
```
I looked at how it's implemented in origin, https://github.com/openshift/origin/blob/master/hack/lib/util/golang.sh#L11
and that doesn't work properly either (it seems to allow any go version, even very old ones), so we shouldn't copy that as-is.

**Comment by jhernand** [comment]
@elad661 I submitted openshift/release#713 to fix that a couple of days ago. It is now merged. Can you back-port it to this repository?

**Comment by elad661** [comment]
@jhernand Thanks, I'll send a PR.

**Pull request merged**
