### PR TITLE
Upgrade observer version, watch for delete events

### PR DESCRIPTION
**Pull request by yaacov**
**Description**

Fix: https://github.com/openshift/autoheal/issues/101

Upgrade to v1.5.11 of observer, watch for create and delete events.

### CODE REVIEW

**Comment by yaacov** [comment]
@nimrodshn @zgalor @moolitayer @elad661 @jhernand . Please review.

**Comment by jhernand** [comment]
@yaacov if I run `make check` with this patch applied I get the following error:

```
$ make check
{ \
hack/verify-gofmt.sh ||r=1;\
hack/verify-govet.sh ||r=1;\
hack/verify-imports.sh ||r=1;\
exit $r ;\
}
[INFO] Detected go version: go version go1.10.1 linux/amd64.
[WARNING] Detected golang version doesn't match required Go version.
[WARNING] This version mismatch could lead to differences in execution between this run and the CI systems.
[INFO] hack/verify-gofmt.sh exited with code 0 after 00h 00m 00s
[INFO] Detected go version: go version go1.10.1 linux/amd64.
[WARNING] Detected golang version doesn't match required Go version.
[WARNING] This version mismatch could lead to differences in execution between this run and the CI systems.
[INFO] hack/verify-govet.sh exited with code 0 after 00h 00m 00s
SUCCESS after 0.012s: hack/verify-imports.sh:18: executing 'import-verifier /files/go/src/github.com/openshift/autoheal/hack/import-restrictions.json' expecting success
[INFO] hack/verify-imports.sh exited with code 0 after 00h 00m 01s
GOTEST_FLAGS="" hack/test-go.sh  
[INFO] [CLEANUP] Cleaning up temporary directories
ok  	github.com/openshift/autoheal/cmd/autoheal	(cached)	coverage: 58.9% of statements
ok  	github.com/openshift/autoheal/pkg/alertmanager	(cached)	coverage: 100.0% of statements
ok  	github.com/openshift/autoheal/pkg/apis/autoheal	(cached)	coverage: 8.0% of statements
E0509 09:59:24.995523    8425 config.go:105] Can't reload configuration files: Can't check if '/tmp/test_dir735571558/test_file0258046093' is a file or a directory: stat /tmp/test_dir735571558/test_file0258046093: no such file or directory
E0509 09:59:25.050732    8425 config.go:105] Can't reload configuration files: Can't check if '/tmp/test_config144561735' is a file or a directory: stat /tmp/test_config144561735: no such file or directory
E0509 09:59:25.050853    8425 config.go:105] Can't reload configuration files: Can't check if '/tmp/test_config144561735' is a file or a directory: stat /tmp/test_config144561735: no such file or directory
E0509 09:59:25.051588    8425 config.go:105] Can't reload configuration files: Can't check if '/tmp/test_config144561735' is a file or a directory: stat /tmp/test_config144561735: no such file or directory
E0509 09:59:25.052407    8425 config.go:105] Can't reload configuration files: Can't check if '/tmp/test_config144561735' is a file or a directory: stat /tmp/test_config144561735: no such file or directory
PASS
coverage: 57.1% of statements
==================
WARNING: DATA RACE
Write at 0x00c42041a600 by goroutine 60:
  github.com/openshift/autoheal/pkg/config.(*RulesConfig).clear()
      /files/go/src/github.com/openshift/autoheal/_output/local/go/src/github.com/openshift/autoheal/pkg/config/rules.go:104 +0xc3
  github.com/openshift/autoheal/pkg/config.(*Config).load()
      /files/go/src/github.com/openshift/autoheal/_output/local/go/src/github.com/openshift/autoheal/pkg/config/config.go:125 +0x103
  github.com/openshift/autoheal/pkg/config.(*Config).watch.func1()
      /files/go/src/github.com/openshift/autoheal/_output/local/go/src/github.com/openshift/autoheal/pkg/config/config.go:103 +0xab

Previous read at 0x00c42041a600 by goroutine 45:
  runtime.convT2Eslice()
      /usr/lib/golang/src/runtime/iface.go:373 +0x0
  github.com/openshift/autoheal/pkg/config.TestLoadDir()
      /files/go/src/github.com/openshift/autoheal/_output/local/go/src/github.com/openshift/autoheal/pkg/config/builder_test.go:390 +0x9aa
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:777 +0x16d

Goroutine 60 (running) created at:
  github.com/openshift/autoheal/vendor/github.com/yaacov/observer/observer.(*Observer).sendEvent()
      /files/go/src/github.com/openshift/autoheal/_output/local/go/src/github.com/openshift/autoheal/vendor/github.com/yaacov/observer/observer/observer.go:192 +0xa0
  github.com/openshift/autoheal/vendor/github.com/yaacov/observer/observer.(*Observer).handleEvent.func1()
      /files/go/src/github.com/openshift/autoheal/_output/local/go/src/github.com/openshift/autoheal/vendor/github.com/yaacov/observer/observer/observer.go:229 +0xe6

Goroutine 45 (finished) created at:
  testing.(*T).Run()
      /usr/lib/golang/src/testing/testing.go:824 +0x564
  testing.runTests.func1()
      /usr/lib/golang/src/testing/testing.go:1063 +0xa4
  testing.tRunner()
      /usr/lib/golang/src/testing/testing.go:777 +0x16d
  testing.runTests()
      /usr/lib/golang/src/testing/testing.go:1061 +0x4e1
  testing.(*M).Run()
      /usr/lib/golang/src/testing/testing.go:978 +0x2cd
  main.main()
      _testmain.go:104 +0x324
==================
E0509 09:59:25.054325    8425 config.go:105] Can't reload configuration files: Can't check if '/tmp/temp_dir467130618' is a file or a directory: stat /tmp/temp_dir467130618: no such file or directory
Found 1 data race(s)
FAIL	github.com/openshift/autoheal/pkg/config	1.096s
ok  	github.com/openshift/autoheal/pkg/dig	(cached)	coverage: 73.9% of statements
ok  	github.com/openshift/autoheal/pkg/memory	(cached)	coverage: 90.0% of statements
[ERROR] PID 8094: hack/test-go.sh:190: `go test ${gotest_flags} ${test_packages}` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/test-go.sh:190: `go test ${gotest_flags} ${test_packages}`
[INFO]   Exiting with code 1.
make: *** [Makefile:92: test-unit] Error 1
```

Can you take a look?

**Comment by yaacov** [comment]
> Can you take a look?

looking :+1:

**Comment by yaacov** [comment]
> Can you take a look?

@jhernand PTAL now

**Comment by jhernand** [comment]
Thanks @yaacov, I don't get the error now, but I still don't see any action when a configuration file is removed. This is what I do to check it:

```
$ # Create an empty configuration directory:
$ mkdir config.d

$ # Start the autoheal service in the background:
$  _output/local/bin/linux/amd64/autoheal server --config-file config.d &
I0509 11:08:40.129114   14815 config.go:97] Watching configuration file 'config.d/*.yml'
I0509 11:08:40.129199   14815 config.go:97] Watching configuration file 'config.d/*.yaml'
I0509 11:08:40.129223   14815 healer.go:132] AWX user is ''
I0509 11:08:40.129234   14815 healer.go:133] AWX project is ''
I0509 11:08:40.129324   14815 healer.go:196] Workers started
W0509 11:08:40.129337   14815 healer.go:254] There are no healing rules in the configuration
I0509 11:08:40.129354   14815 healer.go:213] Web server started
I0509 11:08:40.129416   14815 active_jobs_worker.go:27] Going over active jobs queue

$ # Copy a first configuration file to the configuration directory:
$ cp examples/autoheal-dev.yml config.d/0.yml
I0509 11:09:25.830782   14815 config.go:109] Configuration files have changed
I0509 11:09:25.831166   14815 config.go:193] Loading configuration file 'config.d/0.yml'
I0509 11:09:25.863426   14815 healer.go:252] Loaded 2 healing rules from the configuration
I0509 11:09:25.863503   14815 rules_worker.go:83] Rule 'start-node' was added
I0509 11:09:25.863531   14815 rules_worker.go:83] Rule 'say-hello' was added

$ # Create a second configuration file, with a new rule:
$ cat >> config.d/1.yml <<.
> rules:
> - metadata:
>     name: another-rule
>   labels:
>     alertname: "AnotherAlert"
>   awxJob:
>     template: "Do something"
> .
I0509 11:10:50.559053   14815 config.go:109] Configuration files have changed
I0509 11:10:50.559484   14815 config.go:193] Loading configuration file 'config.d/0.yml'
I0509 11:10:50.562470   14815 config.go:193] Loading configuration file 'config.d/1.yml'
I0509 11:10:50.563518   14815 rules_worker.go:98] Rule 'start-node' was deleted
I0509 11:10:50.563923   14815 rules_worker.go:98] Rule 'say-hello' was deleted
I0509 11:10:50.564028   14815 rules_worker.go:83] Rule 'start-node' was added
I0509 11:10:50.564142   14815 rules_worker.go:83] Rule 'say-hello' was added
I0509 11:10:50.564245   14815 healer.go:252] Loaded 3 healing rules from the configuration
I0509 11:10:50.564331   14815 rules_worker.go:83] Rule 'another-rule' was added

$ # Delete the second configuration file. Should trigger a reload, but nothing happens.
$ rm config.d/1.yml
```

**Comment by yaacov** [comment]
@jhernand 

> Delete the second configuration file. Should trigger a reload, but nothing happens.

Works for me (TM) 
Do you think I check somthing more ?

remove

**Comment by jhernand** [comment]
Ah, I see, I applied only the last commit of your pull request. Now I applied both and it works correctly. Thanks @yaacov.

**Pull request merged**
